#!/bin/sh

SOURCE=/src/repo/src
TARGET=/target

cd ${SOURCE}

make distclean
./configure                \
    --with-features=huge   \
    --enable-perlinterp    \
    --enable-pythoninterp  \
    --enable-rubyinterp    \
    --enable-multibyte     \
    --enable-fontset
make
sudo DESTDIR=${TARGET} make install

# vim: set ai et sw=4 syntax=sh :
